### ISSUE TITLE
Little confusing on a result

### ISSUE THREAD

**Issue by kleinzcy** [saic-vul/ritm_interactive_segmentation#1]
Happy to read your great work again. 

I am confusing about the result in Table 1 and Table 3. In Table 1, it shows that HRNet-18(Conv1S, Disk5) achieve 6.90 on DAVIS. In the first part of ablation studies(section 5.2), you claim that you use HRNet with the Conv1S input scheme and encode clicks with disks of radius 5 in all other experiments. But in Table 3, the DAVIS result of HRNet-18 trained on SBD is 7.17. I don't understand the difference between them.

**Comment by ksofiyuk** [comment]
Thank you for your attention. We retrained all models for the ablation from Table 3 from scratch and didn't reuse models with similar settings from Table 1. The difference in results is due to randomness of training. As you can notice, the Berkley result also differs for these models.

It is likely that there is no much difference between Disk3/5 and Conv1S/E. It is very similar architecture settings and you can use any of these setups and obtain good results, which might differ by the training randomness.

**Comment by kleinzcy** [comment]
I got it. Thanks for your reply.
